### PR TITLE
child_process_stream: Provide custom environment support

### PR DESCRIPTION
**Pull request by ZyX-I**
This is needed for neovim/neovim#4964.

### CODE REVIEW

**Comment by ZyX-I** [comment]
Any changes to tests?

**Comment by justinmk** [comment]
👍  There's not many tests for this client yet, though https://github.com/neovim/lua-client/pull/28 adds many.

Reminder that https://github.com/neovim/lua-client/blob/master/nvim-client-0.0.1-24.rockspec file name and version must be bumped.

**Comment by justinmk** [comment]
Build will fail because of http://stackoverflow.com/a/37559463/152142 , I'll fix that soon.

**Comment by ZyX-I** [comment]
@justinmk Rockspec updated.

**Comment by ZyX-I** [comment]
And builds did not fail.

**Comment by justinmk** [comment]
Oh, http://apt.llvm.org/ is operational again.

**Comment by ZyX-I** [comment]
@justinmk Somebody needs to create a new release, currently `luarocks install --local https://raw.github.com/neovim/lua-client/master/nvim-client-0.0.1-25.rockspec` fails with

```
Using https://raw.github.com/neovim/lua-client/master/nvim-client-0.0.1-25.rockspec... switching to 'build' mode

Error: Error fetching file: Failed downloading https://github.com/neovim/lua-client/archive/0.0.1-25.tar.gz - HTTP/1.1 404 Not Found
```

**Comment by justinmk** [comment]
@tarruda how should that go?

**Comment by ZyX-I** [comment]
@justinmk If I am not mistaking, the minimal action you should do is just add a tag (`0.0.1-25.tar.gz` is a mere `{revspec}.tar.gz`: I may even use `https://github.com/neovim/lua-client/archive/master^{/Bump}.tar.gz`).

**Comment by tarruda** [comment]
@ZyX-I was the problem fixed by tagging 0.0.25?

**Comment by ZyX-I** [comment]
Yes.

**Comment by ZyX-I** [comment]
Only by tagging 0.0.1-25, not 0.0.25.

**Pull request merged**
