### PR TITLE
Add netbsd to rockspec platforms

### PR DESCRIPTION
**Pull request by Pyrohh**
https://github.com/neovim/neovim/issues/3107

### CODE REVIEW

**Comment by justinmk** [comment]
Same problem as https://github.com/neovim/lua-client/pull/12#issuecomment-125174477 but this should be fine to merge.

Thanks!

**Comment by justinmk** [comment]
I think we need a version bump now, e.g. https://github.com/neovim/lua-client/commit/1bcb777a50ab1fb93da6ad5e76baa17c96720361

and then the dep in core will need to be updated.

**Comment by Pyrohh** [comment]
not just yet I think

**Comment by Pyrohh** [comment]
We can just tell @marchelzo to apply a patch which uses the most recent commit instead of a release tag. Allowing the build to happen on netbsd might uncover a build error, like in #2.

**Pull request merged**
