### PR TITLE
[RFC] support async notifications to nvim

### PR DESCRIPTION
**Pull request by bfredl**
needed for testing neovim/neovim#3106

### CODE REVIEW

**Comment by bfredl** [comment]
Failure:

    $ eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) deps-x64"
    Prebuilt dependencies are only supported for OS X.

**Comment by tarruda** [comment]
cc @fwalch 

For now, feel free to change the travis script to build dependencies

In any case, LGTM

**Comment by bfredl** [comment]
Not sure how to go about this, would I just add `CI_TARGET=deps64` below line 25 in `deps-ci/.travis.yml` (and update `deps_x64()` in `travis-setup.sh` as needed) ?

**Comment by justinmk** [comment]
Maybe @fwalch can comment.

**Comment by fwalch** [comment]
Maybe we should just add the x64 linux deps back to the bot-ci build for now, would be the most simple solution, I think.

Or, change this repo to use container builds, remove the `eval` stuff from .travis.yml, just run `make deps` (to clarify, this is with the `lua-client` top-level Makefile) and cache the `.deps` directory.

**Comment by fwalch** [comment]
> Or, change this repo to use container builds, remove the eval stuff from .travis.yml, just run make deps (to clarify, this is with the lua-client top-level Makefile) and cache the .deps directory.

To avoid going out-of-date with the deps (e.g. the Makefile still uses libuv 0.11), it could use the sources from `neovim/deps`.

**Comment by justinmk** [comment]
@bfredl The build should work now, could you rebase this?

**Comment by bfredl** [comment]
Done!

**Pull request merged**
