### PR TITLE
Add support for illumos derivatives such as SmartOS

### PR DESCRIPTION
**Pull request by papertigers**

### CODE REVIEW

**Comment by justinmk** [comment]
Thanks for working on that :)

**Comment by papertigers** [comment]
Sure thing :)
Have a wad coming for neovim itself. 
Missing one piece that I edit by hand.  Not sure how cmake creates it.  Do you know much about cmake?

**Comment by justinmk** [comment]
I know some things about cmake, others on the project know a lot more.

**Comment by papertigers** [comment]
Do you know where linker flags get set?  Need an additional linker arg for solaris/illumos

**Comment by justinmk** [comment]
Here? https://github.com/neovim/neovim/blob/master/CMakeLists.txt#L145-L159

**Comment by papertigers** [comment]
Yep, I found that 10min ago haha.  It worked, so I am doing some more testing.

**Pull request merged**
