### PR TITLE
Update libuv

### PR DESCRIPTION
**Pull request by justinmk**

### CODE REVIEW

**Comment by justinmk** [comment]
BTW, I am baffled about where in our build system is this repo actually pulled in (say for the neovim functional tests). Can someone point me to it?

**Comment by Pyrohh** [comment]
Given the NetBSD thing was never followed up on (see https://github.com/neovim/lua-client/pull/13#issuecomment-125257895), perhaps now would be the time to bump the version?

**Comment by justinmk** [comment]
@Pyrohh Yes, working on it. Also migrating to a container build.

**Comment by Pyrohh** [comment]
Good to hear, and I don't mean to rush you, just a reminder :-)

**Pull request merged**
